SL-982 date comparisions in rules corrected to isAfter and Before instead of greater or less which was causing issues
Before when search runned a few times 10-20 it was throwin exception Caused by: java.lang.NoSuchMethodError: java.time.temporal.Temporal.compareTo(Ljava/time/temporal/Temporal;)I